blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class PublishedManager(models.Manager):
    def queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    published = PublishedManager()
    objects = models.Manager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment added to post {self.post} by {self.name}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {'name': forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
                   'email': forms.EmailInput(attrs={'class': 'uk-input uk-form-width-large'}),
                   'body': forms.Textarea(
                       attrs={'class': 'uk-textarea uk-form-width-large', 'style': 'resize: vertical'})
                   }


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class': 'uk-input uk-form-width-large'}),
                            label="Search Query")

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
# from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'page': page, 'posts': posts, 'tag': tag}
    return render(request, 'blog/post/list.html', context=context)


# class PostListView(ListView):
#     queryset = Post.objects.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)

    # similar posts list
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {'post': post, 'comments': comments, 'similar_posts': similar_posts, 'comment_form': comment_form}
    return render(request, 'blog/post/detail.html', context=context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) invite you to read \"{post.title}\""
            message = f"Read the post \"{post.title}\" on {post_url}\n\n Comment added by {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent
    }
    return render(request, 'blog/post/share.html', context=context)


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)

            results = Post.objects.annotate(
                search=search_vector, rank=SearchRank(search_vector, search_query)).filter(
                search=search_query).order_by('-rank')
            print(results)
    return render(request,
                  'blog/post/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="{% static 'libs/uikit-3.2.6/css/uikit.min.css' %}"/>

    <!-- UIkit JS -->
    <script src="{% static 'libs/uikit-3.2.6/js/uikit.min.js' %}"></script>
    <script src="{% static 'libs/uikit-3.2.6/js/uikit-icons.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<section class="uk-flex" uk-height-viewport="expand: true">
    <main class="uk-card uk-card-default uk-card-body uk-width-1-1">
        {% block content %}
        {% endblock content %}
    </main>
    <aside class="uk-card uk-card-default uk-card-body uk-background-muted uk-padding uk-panel uk-width-1-4">
        <h2 class="uk-tile uk-padding-remove">Welcome to my blog.</h2>
        <p>Total articles posted: {% total_posts %}</p>
        {% show_latest_posts 3 %}

        {% get_most_commented_posts 3 as most_commented_posts %}
        <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
            <li class="uk-nav-header">Most Commented</li>

            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">
                    <span class="uk-margin-small-right"
                          uk-icon="icon: link"></span> {{ post.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="uk-margin-top">
            <a class="uk-link-heading" href="{% url 'blog:post_feed' %}">
                <span class="uk-margin-small-right" uk-icon="icon: rss"></span>
                Subscribe to RSS Feed
            </a>
        </div>
    </aside>
</section>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <div class="uk-container">
        <article class="uk-article">

            <h1 class="uk-article-title">{{ post.title }}</h1>
            <p class="uk-article-meta">Written by {{ post.author }} on
                <time datetime="{{ post.publish }}">{{ post.publish|date:"M d, Y" }}</time>
            </p>
            <p>{{ post.body|markdown }}</p>

            <div class="uk-grid-small uk-child-width-auto" uk-grid>
                <div>
                    <a class="uk-button uk-button-text" href="{% url "blog:post_share" post.id %}">Share Post</a>
                </div>
            </div>

        </article>


        <h3>Similar posts</h3>
        <ul class="uk-subnav uk-subnav-divider" uk-margin>
            {% for post in similar_posts %}

                <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
            {% empty %}
                <p>
                    No similar posts.
                </p>
            {% endfor %}
        </ul>

        {% with comments.count as total_comments %}
            <h3>{{ total_comments }} comment{{ total_comments|pluralize:"s" }}</h3>
        {% endwith %}
        <ul class="uk-comment-list">
            {% for comment in comments %}
                <li>
                    <article
                            class="uk-comment uk-visible-toggle uk-comment-primary"
                            tabindex="-1">
                        <header class="uk-comment-header uk-position-relative">
                            <div class="uk-grid-medium uk-flex-middle" uk-grid>
                                <div class="uk-width-auto">
                                    <img class="uk-comment-avatar"
                                         src="https://avatars.dicebear.com/v2/bottts/example.svg?options[colors][]=cyan"
                                         width="80" height="80" alt="">
                                </div>
                                <div class="uk-width-expand">
                                    <h5 class="uk-comment-meta uk-margin-remove">
                                        <a class="uk-link-reset" href="#">Comment: {{ forloop.counter }} added
                                            by: {{ comment.name }}</a>
                                    </h5>
                                    <p class="uk-comment-meta uk-margin-remove-top">
                                        <a class="uk-link-reset" href="#">{{ comment.created }}</a>
                                    </p>
                                </div>
                            </div>
                        </header>
                        <div class="uk-comment-body">
                            <p>{{ comment.body|linebreaks }}</p>
                        </div>
                    </article>
                </li>
            {% empty %}
                <p>No comments yet.</p>
            {% endfor %}
        </ul>



        {% if new_comment %}
            <h3>Your comment has been added.</h3>
        {% else %}
            <h3>Add new comment</h3>
            <form action="." method="post">
                <fieldset class="uk-fieldset">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="uk-button uk-button-primary">Add Comment</button>
                </fieldset>
            </form>
        {% endif %}
    </div>


{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
    <li class="uk-nav-header">Latest</li>

    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                    <span class="uk-margin-small-right"
                          uk-icon="icon: link"></span> {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
    <div class="uk-container">
        <h1 class="uk-heading-divider">My Blog</h1>

        {% if tag %}
            <h3>Posts filtered by Tag "{{ tag.name }}"</h3>
        {% endif %}
        {% for post in posts %}
            <div class="uk-margin-medium-top uk-card uk-card-hover uk-card-default">
                <div class="uk-card-header">
                    <div class="uk-grid-small uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h3 class="uk-card-title uk-margin-remove-bottom uk-text-primary">
                                <a class="uk-button-text uk-link-heading"
                                   href="{{ post.get_absolute_url }}">{{ post.title }}
                                </a>
                            </h3>
                            <div class="uk-text-meta uk-margin-remove-top">
                                {% for tag in post.tags.all %}
                                    <a class="uk-button uk-button-text"
                                       href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                                    {% if not forloop.last %}&#8226
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="uk-card-body">
                    <p class="uk-text-lead">{{ post.body|markdown|truncatewords_html:30 }}</p>
                </div>
                <div class="uk-card-footer">

                    <p class="uk-text-meta">Posted:
                        <time datetime="{{ post.publish }}">{{ post.publish|date:"M d, Y" }}</time>
                        By: {{ post.author }}</p>
                </div>
            </div>


        {% endfor %}
        {% include "blog/post/pagination.html" with page=posts %}
    </div>

{% endblock %}

blog/templates/blog/post/pagination.html
<ul class="uk-pagination">
    {% if page.has_previous %}
        <li>
            <a href="?page={{ page.previous_page_number }}">
                <span uk-pagination-previous></span>
                Previous
            </a>
        </li>
    {% endif %}
    <span class="current">Page: {{ page.number }}/{{ page.paginator.num_pages }}</span>
    {% if page.has_next %}
        <li>
            <a href="?page={{ page.next_page_number }}">Next
                <span class="uk-margin-small-left" uk-pagination-next></span>
            </a>
        </li>
    {% endif %}
</ul>

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}

{% block content %}
    <div class="uk-container">
        {% if query %}
            <h1 class="uk-heading-divider">Posts containing query "{{ query }}"</h1>
            <h3 class="uk-text-normal">
                {% with results.count as total_results %}
                    Found {{ total_results }} result{{ total_results|pluralize }}
                {% endwith %}
            </h3>
            {% for post in results %}
                <h4 class="uk-text-normal"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                {{ post.body|truncatewords:5 }}
            {% empty %}
                <p>No results for provided query.</p>
            {% endfor %}
            <p><a href="{% url "blog:post_search" %}">Search again</a></p>
        {% else %}
            <h1 class="uk-heading-divider">Search for posts</h1>
            <form action="." method="get">
                <fieldset class="uk-fieldset">
                    {{ form.as_p }}
                    <button type="submit" class="uk-button uk-button-primary">Search</button>
                </fieldset>
            </form>
        {% endif %}
    </div>

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share Post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Message sent</h1>
        <p>Sending a post "{{ post.title }}" to {{ cd.to }} was successful.</p>
    {% else %}
        <h1>Share "{{ post.title }}" via e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send an e-mail">
        </form>
    {% endif %}
{% endblock %}